#!/usr/bin/env bash
# Custom HTTP response header

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t

# Restart after making changes
sudo service nginx restart
