#!/usr/bin/env bash

# Save the signature in a file on your machine i.e. signature.key
sudo apt-key add signature.key

# Add the apt repo
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'

# Update apt
sudo apt-get update

# Now check your available versions
sudo apt-cache policy mysql-server

# Now install mysql 5.7
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
