#!/bin/bash
# Displays all active IPv4 IPs on the machine it’s executed on

# Use the 'ip' command to get the list of network interfaces and their IP addresses
# Filter the lines that contain 'inet ' (IPv4 addresses)
# Extract and print the IPv4 addresses
ip -4 addr | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1
