#!/usr/bin/env bash
# Bash script to create an RSA key pair

# Set the required variables
private_key_name="school"
no_of_bits=4096
passphrase="betty"

# Generate the RSA key pair with specified requirements
ssh-keygen -t rsa -b $no_of_bits -P $passphrase -f $private_key_name

echo "RSA key pair generated successfully."
